### ISSUE TITLE
Does not work with Go 1.14 (Go master)

### ISSUE THREAD

**Issue by bep** [frankban/quicktest#54]
I'm starting to get test failures when testing with "Go tip":

```go
 does not implement testing.TB (wrong type for Cleanup method)
		have Cleanup()
		want Cleanup(func())
```

**Comment by frankban** [comment]
So I discussed a plan forward with Roger (who contributed testing.TB.Cleanup to the stdlib) and we agree that a possible path forward for handling go 1.14 and leveraging the new cleanup functionality is:
- Make Defer use Cleanup if available.
- In which case, add a cleanup function that checks that Done is called (if not already added previously). This actually gives you better guarantees under go1.14 because it'll tell you when you've forgotten to call Done correctly on pre go 1.14 code. Of course Done is not required if you use Cleanup on go 1.14.
- Make it clear in the docs that you either use the new Cleanup (if you have it) or Defer/Done.
- New minor version release.

What do you think?

**Comment by frankban** [comment]
This is now done, released v1.6.0.

**Comment by bep** [comment]
>What do you think?

I don't use the Cleanup functionality, but your suggestions look sensible at first glance. My main motivation behind this issue was to get `*quicktest.C` to support the `testing.TB` interface, as it does now ...
